insert into przystanki (id_przystanku, ulica) values (1, 'Mcbride');
insert into przystanki (id_przystanku, ulica) values (2, 'Thackeray');
insert into przystanki (id_przystanku, ulica) values (3, 'Mccormick');
insert into przystanki (id_przystanku, ulica) values (4, 'Melody');
insert into przystanki (id_przystanku, ulica) values (5, 'Buell');
insert into przystanki (id_przystanku, ulica) values (6, 'Division');
insert into przystanki (id_przystanku, ulica) values (7, 'American Ash');
insert into przystanki (id_przystanku, ulica) values (8, 'Fuller');
insert into przystanki (id_przystanku, ulica) values (9, 'Oxford');
insert into przystanki (id_przystanku, ulica) values (10, 'Manitowish');
insert into przystanki (id_przystanku, ulica) values (11, 'Hovde');
insert into przystanki (id_przystanku, ulica) values (12, 'Superior');
insert into przystanki (id_przystanku, ulica) values (13, 'Stone Corner');
insert into przystanki (id_przystanku, ulica) values (14, 'Grim');
insert into przystanki (id_przystanku, ulica) values (15, 'Artisan');
insert into przystanki (id_przystanku, ulica) values (16, 'Canary');
insert into przystanki (id_przystanku, ulica) values (17, 'Kenwood');
insert into przystanki (id_przystanku, ulica) values (18, 'Hudson');
insert into przystanki (id_przystanku, ulica) values (19, 'Holy Cross');
insert into przystanki (id_przystanku, ulica) values (20, 'Bluejay');
